version: '3'

services:
  card:
    container_name: syde_landing
    image: sepezho/syde_landing
    ports:
      - "8081:80"
    restart: always
  
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 syde_landing


